In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.3751e+13,  4.5808e-41,  1.3751e+13],
        [ 4.5808e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  1.8484e+31],
        [ 1.8370e+25,  1.4603e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.9264,  0.4718,  0.8790],
        [ 0.0858,  0.1352,  0.6245],
        [ 0.5870,  0.3759,  0.3628],
        [ 0.8050,  0.6873,  0.6029],
        [ 0.7276,  0.4151,  0.8210]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.3147, -0.8788, -1.0756],
        [-0.1172,  0.0828, -0.6584],
        [-0.4669, -1.3383,  2.0818],
        [ 0.9350, -0.1836,  1.0097],
        [ 0.5389, -0.3988,  0.1799]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

<font color=blue>**Addition: syntax 1**</font>



In [13]:
import time

In [15]:
y = torch.rand(5, 3)

start = time.time()
print(x + y)
end = time.time()
print('elapsed = ', end - start)

tensor([[-0.6144, -0.3339, -0.9506],
        [ 0.1409,  0.3728, -0.1901],
        [-0.0983, -1.2486,  2.3619],
        [ 1.5210,  0.7518,  1.1331],
        [ 1.0029,  0.2513,  0.2440]])
elapsed =  0.0007987022399902344


<font color=blue>**Addition: syntax 2**</font>



In [16]:
start = time.time()
print(torch.add(x, y))
end = time.time()
print('elapsed = ', end - start)

tensor([[-0.6144, -0.3339, -0.9506],
        [ 0.1409,  0.3728, -0.1901],
        [-0.0983, -1.2486,  2.3619],
        [ 1.5210,  0.7518,  1.1331],
        [ 1.0029,  0.2513,  0.2440]])
elapsed =  0.0011882781982421875


<font color=blue>**Addition: providing an output tensor as argument**</font>



In [17]:
result = torch.empty(5, 3)

start = time.time()
torch.add(x, y, out=result)
print(result)
end = time.time()
print('elapsed = ', end - start)

tensor([[-0.6144, -0.3339, -0.9506],
        [ 0.1409,  0.3728, -0.1901],
        [-0.0983, -1.2486,  2.3619],
        [ 1.5210,  0.7518,  1.1331],
        [ 1.0029,  0.2513,  0.2440]])
elapsed =  0.0009465217590332031


<font color=blue>**Addition: in-place**</font>



In [18]:
start = time.time()
# adds x to y
y.add_(x)
print(y)
end = time.time()
print('elapsed = ', end - start)

tensor([[-0.6144, -0.3339, -0.9506],
        [ 0.1409,  0.3728, -0.1901],
        [-0.0983, -1.2486,  2.3619],
        [ 1.5210,  0.7518,  1.1331],
        [ 1.0029,  0.2513,  0.2440]])
elapsed =  0.003528118133544922


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [20]:
print(x)
print(x[:, 1]) # fetch 1st column

tensor([[-1.3147, -0.8788, -1.0756],
        [-0.1172,  0.0828, -0.6584],
        [-0.4669, -1.3383,  2.0818],
        [ 0.9350, -0.1836,  1.0097],
        [ 0.5389, -0.3988,  0.1799]])
tensor([-0.8788,  0.0828, -1.3383, -0.1836, -0.3988])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1480])
-1.1480324268341064


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described https://pytorch.org/docs/torch.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

### <font color=blue>Converting a Torch Tensor to a NumPy Array</font>


In [23]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [26]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


See how the numpy array changed in value.



In [28]:
a.add_(1)
print('a=', a)
print('a=', type(a))
print('b=', b)
print('b=', type(b))

a= tensor([ 3.,  3.,  3.,  3.,  3.])
a= <class 'torch.Tensor'>
b= [3. 3. 3. 3. 3.]
b= <class 'numpy.ndarray'>


### <font color=blue>Converting NumPy Array to Torch Tensor</font>

See how changing the np array changed the Torch Tensor automatically



In [32]:
import numpy as np
a = np.ones(5)
print('a=', a)
b = torch.from_numpy(a)
print('b=', b)

np.add(a, 1, out=a)
print('a=', a)
print('b=', b)

a= [1. 1. 1. 1. 1.]
b= tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)
a= [2. 2. 2. 2. 2.]
b= tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


<font color=red>All the Tensors on the CPU except a <font color=orange>CharTensor</font> support converting to NumPy and back.</font>

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [34]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print('z=', z)
    print('z=', z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

z= tensor([-0.1480], device='cuda:0')
z= tensor([-0.1480], dtype=torch.float64)
